[package]
name = "alfred-pinboard-rs"
version = "0.12.5"
authors = ["Hamid Ghadyani <hamid@hamid.cc>"]

[dependencies]
# We'll use git until rusty-pin is published as a crate (if ever?!)
# rusty-pin = { git = "ssh://git@github.com:22/spamwax/rusty-pin.git", branch = "master" }
rusty-pin = { git = "https://github.com/spamwax/rusty-pin", branch = "master" }
# rusty-pin = { path = "../rusty-pin" }
# alfred = "4.0.1"
alfred = { path = "../alfred-rs" , features = ["updater"]}
chrono = { version = "0.4", features = ["serde"] }

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

structopt = "0.2"

semver = "0.9"

failure = "0.1.1"

if_chain = "0.1.2"

log = "0.4"
env_logger = "0.5.3"

clippy = { version = "*", optional = true }

[features]
dev = ["clippy"]

