[package]
name = "alfred-pinboard-rs"
version = "0.1.0"
authors = ["Hamid Ghadyani <hamid@hamid.cc>"]

[dependencies]
# rusty-pin = { git = "ssh://git@github.com:22/spamwax/rusty-pin.git", branch = "lib" }
rusty-pin = { git = "ssh://git@git.hamid.cc:22/rust/rusty-pin.git", branch = "lib" }
alfred = "4.0.1"
chrono = { version = "0.4", features = ["serde"] }

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

structopt = "0.1.6"
structopt-derive = "0.1.6"

semver = "0.7.0"

failure = "0.1.1"

log = "0.4"
env_logger = "0.5.3"

clippy = { version = "*", optional = true }

[features]
dev = ["clippy"]

